project:
  type: website
  output-dir: docs

website:
  title: "Note of myself"
  google-analytics: "G-D7YERGZ04Y"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/tranquil-morning
      - icon: linkedin
        href: https://www.linkedin.com/in/tranquil-morning/
      - icon: instagram
        href: https://www.instagram.com/zzang_jinuk/
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

